/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Empresa.Empresa;
import Interfaces.clases.Drive_Labels;
import Interfaces.clases.Empresa_Labels;
import Interfaces.clases.Empresa_Trabajadores;
import Interfaces.clases.Ganancias_Labels;
import Interfaces.clases.Grafico_Utilidad;
import Trabajadores.TipoTrabajador_Estudio;
import Utils.FuncionesSpinner;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import org.jfree.chart.ChartPanel;
import org.jfree.data.xy.XYDataset;

/**
 *
 * @author valeriazampetti
 */
public class Interfaz1 extends javax.swing.JFrame {

    static ChartPanel chartUtilidades_Disney;
    static ChartPanel chartUtilidades;

    static Empresa[] empresas;

    private boolean ignoreListeners = false;
    final JSpinner[] spinners_Trabajadores_Star;
    final JSpinner[] spinners_Trabajadores_Disney;

    /**
     * Creates new form Interfaz1
     *
     * @param trabajadores_Disney
     * @param trabajadores_Star_Channel
     */
    public Interfaz1(Empresa_Trabajadores trabajadores_Disney,
            Empresa_Trabajadores trabajadores_Star_Channel) {
        initComponents();

        this.spinners_Trabajadores_Star = new JSpinner[]{guionista_Star_Spinner,
            disenador_Star_Spinner, animador_Star_Spinner, doblaje_Star_Spinner,
            plotTwist_Star_Spinner, ensamblador_Star_Spinner
        };
        this.spinners_Trabajadores_Disney = new JSpinner[]{guionista_Disney_Spinner,
            disenador_Disney_Spinner, animador_Disney_Spinner, doblaje_Disney_Spinner,
            plotTwist_Disney_Spinner, ensamblador_Disney_Spinner
        };

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.crearEmpresas(trabajadores_Disney, trabajadores_Star_Channel);

        this.crearGrafico();
    }

    private void crearEmpresas(Empresa_Trabajadores trabajadores_Disney,
            Empresa_Trabajadores trabajadores_Star_Channel) {
        var labels = new Empresa_Labels[]{
            new Empresa_Labels(
            new Drive_Labels(Star_Estandar_Field, Star_PlotTwist_Field,
            guiones_Field, doblajes_Field, escenarios_Field,
            animaciones_Field, plotTwist_Field),
            new Ganancias_Labels(Ganancias_Field, Costos_Field, Utilidades_Field),
            field_Viendo_Anime, field_FaltasPM, field_DescontadoPM,
            field_VigilandoDirector,
            field_Contador
            ),
            new Empresa_Labels(
            new Drive_Labels(Star_Disney_Field2, Disney_PlotTwist_Field2,
            guiones_Field2, doblajes_Field2, escenarios_Field2,
            animaciones_Field2, plotTwist_Field2),
            new Ganancias_Labels(Ganancias_Field2, Costos_Field2, Utilidades_Field2),
            field_Viendo_Anime2, field_FaltasPM2, field_DescontadoPM2, field_VigilandoDirector2, field_Contador_Disney_Channel
            ),};

        empresas = new Empresa[]{
            new Empresa(6, "Star Channel", labels[0], trabajadores_Star_Channel,
            new int[50], () -> {
                crearGrafico();
            }, InterfazInicial.dias_Contador),
            new Empresa(1, "Disney Channel", labels[1], trabajadores_Disney,
            new int[50], () -> {
                crearGrafico();
            }, InterfazInicial.dias_Contador)
        };

        for (int i = 0; i < empresas.length; i++) {
            var empresa = empresas[i];
            this.TabbedPane_principal.setTitleAt(i, empresa.nombre);
        }

        this.conectarSpinnersEmpresa(spinners_Trabajadores_Star, empresas[0],
                InterfazInicial.max_Empleados_Star);
        this.conectarSpinnersEmpresa(spinners_Trabajadores_Disney, empresas[1],
                InterfazInicial.max_Empleados_Disney);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        TabbedPane_principal = new javax.swing.JTabbedPane();
        Star_Pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Star_PlotTwist_Field = new javax.swing.JTextField();
        escenarios_Field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Star_Estandar_Field = new javax.swing.JTextField();
        animaciones_Field = new javax.swing.JTextField();
        doblajes_Field = new javax.swing.JTextField();
        plotTwist_Field = new javax.swing.JTextField();
        guiones_Field = new javax.swing.JTextField();
        guiones_FieldMAX = new javax.swing.JTextField();
        escenarios_FieldMAX = new javax.swing.JTextField();
        animaciones_FieldMAX = new javax.swing.JTextField();
        doblajes_FieldMAX = new javax.swing.JTextField();
        plotTwist_FieldMAX = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        field_Viendo_Anime = new javax.swing.JTextField();
        field_VigilandoDirector = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        field_Contador = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Chart_Panel = new javax.swing.JPanel();
        field_FaltasPM = new javax.swing.JTextField();
        field_DescontadoPM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Utilidades_Field = new javax.swing.JTextField();
        Ganancias_Field = new javax.swing.JTextField();
        Costos_Field = new javax.swing.JTextField();
        guionista_Star_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel36 = new javax.swing.JLabel();
        disenador_Star_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel37 = new javax.swing.JLabel();
        animador_Star_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel38 = new javax.swing.JLabel();
        doblaje_Star_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel39 = new javax.swing.JLabel();
        plotTwist_Star_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel40 = new javax.swing.JLabel();
        ensamblador_Star_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel41 = new javax.swing.JLabel();
        Star_Fondo = new javax.swing.JLabel();
        Disney_Pane = new javax.swing.JPanel();
        field_Contador_Disney_Channel = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        field_Viendo_Anime2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        field_DescontadoPM2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        field_FaltasPM2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        field_VigilandoDirector2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        guiones_Field2 = new javax.swing.JTextField();
        guiones_FieldMAX2 = new javax.swing.JTextField();
        escenarios_Field2 = new javax.swing.JTextField();
        animaciones_Field2 = new javax.swing.JTextField();
        doblajes_Field2 = new javax.swing.JTextField();
        plotTwist_Field2 = new javax.swing.JTextField();
        escenarios_FieldMAX2 = new javax.swing.JTextField();
        animaciones_FieldMAX22 = new javax.swing.JTextField();
        doblajes_FieldMAX2 = new javax.swing.JTextField();
        animaciones_FieldMAX2 = new javax.swing.JTextField();
        plotTwist_FieldMAX2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Star_Disney_Field2 = new javax.swing.JTextField();
        Disney_PlotTwist_Field2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Utilidades_Field2 = new javax.swing.JTextField();
        Costos_Field2 = new javax.swing.JTextField();
        Ganancias_Field2 = new javax.swing.JTextField();
        guionista_Disney_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel42 = new javax.swing.JLabel();
        disenador_Disney_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel43 = new javax.swing.JLabel();
        animador_Disney_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel44 = new javax.swing.JLabel();
        doblaje_Disney_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel45 = new javax.swing.JLabel();
        plotTwist_Disney_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel46 = new javax.swing.JLabel();
        ensamblador_Disney_Spinner = new javax.swing.JSpinner(
            new SpinnerNumberModel(1, 1, InterfazInicial.max_Empleados_Star, 1)
        );
        jLabel47 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jLabel15.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabbedPane_principal.setAutoscrolls(true);

        Star_Pane.setAutoscrolls(true);
        Star_Pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Capitulos listos para entregar");
        Star_Pane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Plot Twist");
        Star_Pane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Estándar");
        Star_Pane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        Star_PlotTwist_Field.setEditable(false);
        Star_PlotTwist_Field.setText("0");
        Star_PlotTwist_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star_PlotTwist_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(Star_PlotTwist_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        escenarios_Field.setEditable(false);
        escenarios_Field.setText("0");
        escenarios_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escenarios_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(escenarios_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel6.setText("Recursos del Drive");
        Star_Pane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jLabel7.setText("Actuales");
        Star_Pane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jLabel8.setText("Máximo");
        Star_Pane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        Star_Estandar_Field.setEditable(false);
        Star_Estandar_Field.setText("0");
        Star_Estandar_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star_Estandar_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(Star_Estandar_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        animaciones_Field.setEditable(false);
        animaciones_Field.setText("0");
        animaciones_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animaciones_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(animaciones_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        doblajes_Field.setEditable(false);
        doblajes_Field.setText("0");
        doblajes_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doblajes_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(doblajes_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        plotTwist_Field.setEditable(false);
        plotTwist_Field.setText("0");
        plotTwist_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotTwist_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(plotTwist_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        guiones_Field.setEditable(false);
        guiones_Field.setText("0");
        guiones_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiones_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(guiones_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        guiones_FieldMAX.setEditable(false);
        guiones_FieldMAX.setText("25");
        guiones_FieldMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiones_FieldMAXActionPerformed(evt);
            }
        });
        Star_Pane.add(guiones_FieldMAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        escenarios_FieldMAX.setEditable(false);
        escenarios_FieldMAX.setText("20");
        escenarios_FieldMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escenarios_FieldMAXActionPerformed(evt);
            }
        });
        Star_Pane.add(escenarios_FieldMAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        animaciones_FieldMAX.setEditable(false);
        animaciones_FieldMAX.setText("55");
        animaciones_FieldMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animaciones_FieldMAXActionPerformed(evt);
            }
        });
        Star_Pane.add(animaciones_FieldMAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        doblajes_FieldMAX.setEditable(false);
        doblajes_FieldMAX.setText("35");
        doblajes_FieldMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doblajes_FieldMAXActionPerformed(evt);
            }
        });
        Star_Pane.add(doblajes_FieldMAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        plotTwist_FieldMAX.setEditable(false);
        plotTwist_FieldMAX.setText("10");
        plotTwist_FieldMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotTwist_FieldMAXActionPerformed(evt);
            }
        });
        Star_Pane.add(plotTwist_FieldMAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jLabel9.setText("Escenarios");
        Star_Pane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jLabel10.setText("Guiones");
        Star_Pane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel11.setText("Plot Twists");
        Star_Pane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jLabel12.setText("Doblajes");
        Star_Pane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel13.setText("Animaciones");
        Star_Pane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        field_Viendo_Anime.setEditable(false);
        field_Viendo_Anime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_Viendo_AnimeActionPerformed(evt);
            }
        });
        Star_Pane.add(field_Viendo_Anime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, -1));

        field_VigilandoDirector.setEditable(false);
        field_VigilandoDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_VigilandoDirectorActionPerformed(evt);
            }
        });
        Star_Pane.add(field_VigilandoDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, -1));

        jLabel14.setText("Contador: ");
        Star_Pane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        field_Contador.setEditable(false);
        field_Contador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_ContadorActionPerformed(evt);
            }
        });
        Star_Pane.add(field_Contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel16.setText("Estado del Director");
        Star_Pane.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel17.setText("Estado del Project Manager");
        Star_Pane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel18.setText("Faltas ");
        Star_Pane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel19.setText("Dinero descontado");
        Star_Pane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        Star_Pane.add(Chart_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 340, 260));

        field_FaltasPM.setEditable(false);
        field_FaltasPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_FaltasPMActionPerformed(evt);
            }
        });
        Star_Pane.add(field_FaltasPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        field_DescontadoPM.setEditable(false);
        field_DescontadoPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_DescontadoPMActionPerformed(evt);
            }
        });
        Star_Pane.add(field_DescontadoPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 70, -1));

        jLabel5.setText("Utilidades totales");
        Star_Pane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        jLabel20.setText("Ganancias en bruto");
        Star_Pane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel21.setText("Costos Operativos");
        Star_Pane.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        Utilidades_Field.setEditable(false);
        Utilidades_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Utilidades_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(Utilidades_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, -1));

        Ganancias_Field.setEditable(false);
        Ganancias_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ganancias_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(Ganancias_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        Costos_Field.setEditable(false);
        Costos_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Costos_FieldActionPerformed(evt);
            }
        });
        Star_Pane.add(Costos_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));
        Star_Pane.add(guionista_Star_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Guionista");
        Star_Pane.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));
        Star_Pane.add(disenador_Star_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Diseñador escenario");
        Star_Pane.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));
        Star_Pane.add(animador_Star_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, -1, -1));

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Animador");
        Star_Pane.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, -1));
        Star_Pane.add(doblaje_Star_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Actor Doblaje");
        Star_Pane.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, -1, 20));
        Star_Pane.add(plotTwist_Star_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Plot Twist");
        Star_Pane.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, -1, -1));
        Star_Pane.add(ensamblador_Star_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, -1));

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Ensamblador");
        Star_Pane.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, -1));

        Star_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/starplusfondo2.jpg"))); // NOI18N
        Star_Pane.add(Star_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 980, 540));

        TabbedPane_principal.addTab("tab2", Star_Pane);

        Disney_Pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_Contador_Disney_Channel.setEditable(false);
        field_Contador_Disney_Channel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_Contador_Disney_ChannelActionPerformed(evt);
            }
        });
        Disney_Pane.add(field_Contador_Disney_Channel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel23.setText("Contador: ");
        Disney_Pane.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        field_Viendo_Anime2.setEditable(false);
        field_Viendo_Anime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_Viendo_Anime2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(field_Viendo_Anime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, -1));

        jLabel24.setText("Estado del Project Manager");
        Disney_Pane.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        field_DescontadoPM2.setEditable(false);
        field_DescontadoPM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_DescontadoPM2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(field_DescontadoPM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 70, -1));

        jLabel25.setText("Faltas ");
        Disney_Pane.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        field_FaltasPM2.setEditable(false);
        field_FaltasPM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_FaltasPM2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(field_FaltasPM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel26.setText("Dinero descontado");
        Disney_Pane.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        field_VigilandoDirector2.setEditable(false);
        field_VigilandoDirector2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_VigilandoDirector2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(field_VigilandoDirector2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, -1));

        jLabel27.setText("Estado del Director");
        Disney_Pane.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel28.setText("Recursos del Drive");
        Disney_Pane.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jLabel29.setText("Actuales");
        Disney_Pane.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jLabel30.setText("Máximo");
        Disney_Pane.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        guiones_Field2.setEditable(false);
        guiones_Field2.setText("0");
        guiones_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiones_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(guiones_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        guiones_FieldMAX2.setEditable(false);
        guiones_FieldMAX2.setText("25");
        guiones_FieldMAX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiones_FieldMAX2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(guiones_FieldMAX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        escenarios_Field2.setEditable(false);
        escenarios_Field2.setText("0");
        escenarios_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escenarios_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(escenarios_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        animaciones_Field2.setEditable(false);
        animaciones_Field2.setText("0");
        animaciones_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animaciones_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(animaciones_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        doblajes_Field2.setEditable(false);
        doblajes_Field2.setText("0");
        doblajes_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doblajes_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(doblajes_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        plotTwist_Field2.setEditable(false);
        plotTwist_Field2.setText("0");
        plotTwist_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotTwist_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(plotTwist_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        escenarios_FieldMAX2.setEditable(false);
        escenarios_FieldMAX2.setText("20");
        escenarios_FieldMAX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escenarios_FieldMAX2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(escenarios_FieldMAX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        animaciones_FieldMAX22.setEditable(false);
        animaciones_FieldMAX22.setText("55");
        animaciones_FieldMAX22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animaciones_FieldMAX22ActionPerformed(evt);
            }
        });
        Disney_Pane.add(animaciones_FieldMAX22, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        doblajes_FieldMAX2.setEditable(false);
        doblajes_FieldMAX2.setText("35");
        doblajes_FieldMAX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doblajes_FieldMAX2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(doblajes_FieldMAX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        animaciones_FieldMAX2.setEditable(false);
        animaciones_FieldMAX2.setText("55");
        animaciones_FieldMAX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animaciones_FieldMAX2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(animaciones_FieldMAX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        plotTwist_FieldMAX2.setEditable(false);
        plotTwist_FieldMAX2.setText("10");
        plotTwist_FieldMAX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotTwist_FieldMAX2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(plotTwist_FieldMAX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jLabel4.setText("Capitulos listos para entregar");
        Disney_Pane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Estándar");
        Disney_Pane.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Plot Twist");
        Disney_Pane.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, -1));

        Star_Disney_Field2.setEditable(false);
        Star_Disney_Field2.setText("0");
        Star_Disney_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star_Disney_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(Star_Disney_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        Disney_PlotTwist_Field2.setEditable(false);
        Disney_PlotTwist_Field2.setText("0");
        Disney_PlotTwist_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Disney_PlotTwist_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(Disney_PlotTwist_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel33.setText("Ganancias en bruto");
        Disney_Pane.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel34.setText("Costos Operativos");
        Disney_Pane.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        jLabel35.setText("Utilidades totales");
        Disney_Pane.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        Utilidades_Field2.setEditable(false);
        Utilidades_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Utilidades_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(Utilidades_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, -1));

        Costos_Field2.setEditable(false);
        Costos_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Costos_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(Costos_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        Ganancias_Field2.setEditable(false);
        Ganancias_Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ganancias_Field2ActionPerformed(evt);
            }
        });
        Disney_Pane.add(Ganancias_Field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));
        Disney_Pane.add(guionista_Disney_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Guionista");
        Disney_Pane.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));
        Disney_Pane.add(disenador_Disney_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        jLabel43.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Diseñador escenario");
        Disney_Pane.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));
        Disney_Pane.add(animador_Disney_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, -1, -1));

        jLabel44.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Animador");
        Disney_Pane.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, -1));
        Disney_Pane.add(doblaje_Disney_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        jLabel45.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Actor Doblaje");
        Disney_Pane.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, -1, 20));
        Disney_Pane.add(plotTwist_Disney_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));

        jLabel46.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Plot Twist");
        Disney_Pane.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, -1, -1));
        Disney_Pane.add(ensamblador_Disney_Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, -1));

        jLabel47.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Ensamblador");
        Disney_Pane.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disneyfondo.jpg"))); // NOI18N
        Disney_Pane.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -40, 1020, -1));

        TabbedPane_principal.addTab("tab2", Disney_Pane);

        getContentPane().add(TabbedPane_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escenarios_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escenarios_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escenarios_FieldActionPerformed

    private void Star_PlotTwist_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star_PlotTwist_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Star_PlotTwist_FieldActionPerformed

    private void Star_Estandar_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star_Estandar_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Star_Estandar_FieldActionPerformed

    private void animaciones_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animaciones_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animaciones_FieldActionPerformed

    private void doblajes_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doblajes_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doblajes_FieldActionPerformed

    private void plotTwist_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotTwist_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plotTwist_FieldActionPerformed

    private void guiones_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiones_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiones_FieldActionPerformed

    private void guiones_FieldMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiones_FieldMAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiones_FieldMAXActionPerformed

    private void escenarios_FieldMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escenarios_FieldMAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escenarios_FieldMAXActionPerformed

    private void animaciones_FieldMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animaciones_FieldMAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animaciones_FieldMAXActionPerformed

    private void doblajes_FieldMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doblajes_FieldMAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doblajes_FieldMAXActionPerformed

    private void plotTwist_FieldMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotTwist_FieldMAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plotTwist_FieldMAXActionPerformed

    private void field_Viendo_AnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_Viendo_AnimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_Viendo_AnimeActionPerformed

    private void field_VigilandoDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_VigilandoDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_VigilandoDirectorActionPerformed

    private void field_ContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_ContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_ContadorActionPerformed

    private void field_FaltasPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_FaltasPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_FaltasPMActionPerformed

    private void field_DescontadoPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_DescontadoPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_DescontadoPMActionPerformed

    private void Utilidades_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Utilidades_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Utilidades_FieldActionPerformed

    private void Ganancias_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ganancias_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ganancias_FieldActionPerformed

    private void Costos_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Costos_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Costos_FieldActionPerformed

    private void field_Contador_Disney_ChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_Contador_Disney_ChannelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_Contador_Disney_ChannelActionPerformed

    private void field_Viendo_Anime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_Viendo_Anime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_Viendo_Anime2ActionPerformed

    private void field_DescontadoPM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_DescontadoPM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_DescontadoPM2ActionPerformed

    private void field_FaltasPM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_FaltasPM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_FaltasPM2ActionPerformed

    private void field_VigilandoDirector2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_VigilandoDirector2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_VigilandoDirector2ActionPerformed

    private void guiones_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiones_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiones_Field2ActionPerformed

    private void guiones_FieldMAX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiones_FieldMAX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiones_FieldMAX2ActionPerformed

    private void escenarios_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escenarios_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escenarios_Field2ActionPerformed

    private void animaciones_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animaciones_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animaciones_Field2ActionPerformed

    private void doblajes_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doblajes_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doblajes_Field2ActionPerformed

    private void plotTwist_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotTwist_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plotTwist_Field2ActionPerformed

    private void escenarios_FieldMAX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escenarios_FieldMAX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escenarios_FieldMAX2ActionPerformed

    private void animaciones_FieldMAX22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animaciones_FieldMAX22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animaciones_FieldMAX22ActionPerformed

    private void doblajes_FieldMAX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doblajes_FieldMAX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doblajes_FieldMAX2ActionPerformed

    private void animaciones_FieldMAX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animaciones_FieldMAX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animaciones_FieldMAX2ActionPerformed

    private void plotTwist_FieldMAX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotTwist_FieldMAX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plotTwist_FieldMAX2ActionPerformed

    private void Star_Disney_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star_Disney_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Star_Disney_Field2ActionPerformed

    private void Disney_PlotTwist_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Disney_PlotTwist_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Disney_PlotTwist_Field2ActionPerformed

    private void Utilidades_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Utilidades_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Utilidades_Field2ActionPerformed

    private void Costos_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Costos_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Costos_Field2ActionPerformed

    private void Ganancias_Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ganancias_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ganancias_Field2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Empresa_Trabajadores trabajadores_Disney,
                    Empresa_Trabajadores trabajadores_Star_Channel) {
                new Interfaz1(trabajadores_Disney, trabajadores_Star_Channel).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    private void conectarSpinnersEmpresa(JSpinner[] spinners,
            Empresa empresa, int max_Empleados) {
        spinners[0].addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            if (ignoreListeners) {
                return;
            }
            var cantidad = (int) spinners[0].getValue();
            empresa.modificarEmpleados(cantidad, TipoTrabajador_Estudio.GUIONISTA);

            ignoreListeners = true;
            FuncionesSpinner.set_Maximum_Spinner(spinners, max_Empleados);
            ignoreListeners = false;
        });

        spinners[1].addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            if (ignoreListeners) {
                return;
            }
            var cantidad = (int) spinners[1].getValue();
            System.out.println("DISENADOR_ESCENARIODISENADOR_ESCENARIO");

            empresa.modificarEmpleados(cantidad, TipoTrabajador_Estudio.DISENADOR_ESCENARIO);

            ignoreListeners = true;
            FuncionesSpinner.set_Maximum_Spinner(spinners, max_Empleados);
            ignoreListeners = false;
        });

        spinners[2].addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            if (ignoreListeners) {
                return;
            }
            var cantidad = (int) spinners[2].getValue();
            System.out.println("ANIMADORANIMADORANIMADORANIMADOR");

            empresa.modificarEmpleados(cantidad, TipoTrabajador_Estudio.ANIMADOR);

            ignoreListeners = true;
            FuncionesSpinner.set_Maximum_Spinner(spinners, max_Empleados);
            ignoreListeners = false;
        });

        spinners[3].addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            if (ignoreListeners) {
                return;
            }
            var cantidad = (int) spinners[3].getValue();
            System.out.println("ACTOR_DOBLAJEACTOR_DOBLAJEACTOR_DOBLAJE" + cantidad);

            empresa.modificarEmpleados(cantidad, TipoTrabajador_Estudio.ACTOR_DOBLAJE);

            ignoreListeners = true;
            FuncionesSpinner.set_Maximum_Spinner(spinners, max_Empleados);
            ignoreListeners = false;
        });

        spinners[4].addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            if (ignoreListeners) {
                return;
            }
            var cantidad = (int) spinners[4].getValue();
            System.out.println("PLOT_TWISTPLOT_TWISTPLOT_TWISTPLOT_TWISTPLOT_TWIST");

            empresa.modificarEmpleados(cantidad, TipoTrabajador_Estudio.PLOT_TWIST);

            ignoreListeners = true;
            FuncionesSpinner.set_Maximum_Spinner(spinners, max_Empleados);
            ignoreListeners = false;
        });

        spinners[5].addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            if (ignoreListeners) {
                return;
            }
            var cantidad = (int) spinners[5].getValue();
            System.out.println("ENSAMBLADORENSAMBLADORENSAMBLADORENSAMBLADORENSAMBLADOR");

            empresa.modificarEmpleados(cantidad, TipoTrabajador_Estudio.ENSAMBLADOR);

            ignoreListeners = true;
            FuncionesSpinner.set_Maximum_Spinner(spinners, max_Empleados);
            ignoreListeners = false;
        });
    }

    private void crearGrafico() {
        chartUtilidades_Disney = chartUtilidades = Grafico_Utilidad.createUtilityXYChart("Utilidades en el tiempo",
                Chart_Panel.getSize(),
                Interfaz1.empresas[0].getUtilidades_En_El_Tiempo(), Interfaz1.empresas[1].getUtilidades_En_El_Tiempo());

        Chart_Panel.removeAll();
        Chart_Panel.add(chartUtilidades);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Chart_Panel;
    private javax.swing.JTextField Costos_Field;
    private javax.swing.JTextField Costos_Field2;
    private javax.swing.JPanel Disney_Pane;
    private javax.swing.JTextField Disney_PlotTwist_Field2;
    private javax.swing.JTextField Ganancias_Field;
    private javax.swing.JTextField Ganancias_Field2;
    private javax.swing.JTextField Star_Disney_Field2;
    private javax.swing.JTextField Star_Estandar_Field;
    private javax.swing.JLabel Star_Fondo;
    private javax.swing.JPanel Star_Pane;
    private javax.swing.JTextField Star_PlotTwist_Field;
    private javax.swing.JTabbedPane TabbedPane_principal;
    private javax.swing.JTextField Utilidades_Field;
    private javax.swing.JTextField Utilidades_Field2;
    private javax.swing.JTextField animaciones_Field;
    private javax.swing.JTextField animaciones_Field2;
    private javax.swing.JTextField animaciones_FieldMAX;
    private javax.swing.JTextField animaciones_FieldMAX2;
    private javax.swing.JTextField animaciones_FieldMAX22;
    private javax.swing.JSpinner animador_Disney_Spinner;
    private javax.swing.JSpinner animador_Star_Spinner;
    private javax.swing.JSpinner disenador_Disney_Spinner;
    private javax.swing.JSpinner disenador_Star_Spinner;
    private javax.swing.JSpinner doblaje_Disney_Spinner;
    private javax.swing.JSpinner doblaje_Star_Spinner;
    private javax.swing.JTextField doblajes_Field;
    private javax.swing.JTextField doblajes_Field2;
    private javax.swing.JTextField doblajes_FieldMAX;
    private javax.swing.JTextField doblajes_FieldMAX2;
    private javax.swing.JSpinner ensamblador_Disney_Spinner;
    private javax.swing.JSpinner ensamblador_Star_Spinner;
    private javax.swing.JTextField escenarios_Field;
    private javax.swing.JTextField escenarios_Field2;
    private javax.swing.JTextField escenarios_FieldMAX;
    private javax.swing.JTextField escenarios_FieldMAX2;
    private javax.swing.JTextField field_Contador;
    private javax.swing.JTextField field_Contador_Disney_Channel;
    private javax.swing.JTextField field_DescontadoPM;
    private javax.swing.JTextField field_DescontadoPM2;
    private javax.swing.JTextField field_FaltasPM;
    private javax.swing.JTextField field_FaltasPM2;
    private javax.swing.JTextField field_Viendo_Anime;
    private javax.swing.JTextField field_Viendo_Anime2;
    private javax.swing.JTextField field_VigilandoDirector;
    private javax.swing.JTextField field_VigilandoDirector2;
    private javax.swing.JTextField guiones_Field;
    private javax.swing.JTextField guiones_Field2;
    private javax.swing.JTextField guiones_FieldMAX;
    private javax.swing.JTextField guiones_FieldMAX2;
    private javax.swing.JSpinner guionista_Disney_Spinner;
    private javax.swing.JSpinner guionista_Star_Spinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner plotTwist_Disney_Spinner;
    private javax.swing.JTextField plotTwist_Field;
    private javax.swing.JTextField plotTwist_Field2;
    private javax.swing.JTextField plotTwist_FieldMAX;
    private javax.swing.JTextField plotTwist_FieldMAX2;
    private javax.swing.JSpinner plotTwist_Star_Spinner;
    // End of variables declaration//GEN-END:variables
}
